name: Build and test on PR
on: [pull_request]

jobs:
  main:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd functions && npm ci
      - name: Check lint
        run: cd functions && npm run lint
      - name: Build
        run: cd functions && npm run build
