name: Deploy to live project
on:
  release:
    types: [published]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd functions && npm ci
      - name: use firebase project
        uses: w9jds/firebase-action@master
        with:
          args: use ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.applicationid=${{ secrets.PLANNING_CENTER_APPLICATION_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.secret=${{ secrets.PLANNING_CENTER_SECRET }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.baseurl=${{ secrets.PLANNING_CENTER_BASE_URL }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
