name: Deploy the main branch
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./functions/package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR:  'functions'
      - name: 'cat package.json'
        run: cat ./functions/package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd functions && npm ci
      - name: use firebase project
        uses: w9jds/firebase-action@master
        with:
          args: use ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.applicationid=${{ secrets.PLANNING_CENTER_APPLICATION_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.secret=${{ secrets.PLANNING_CENTER_SECRET }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set environment configuration
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set planningcenter.baseurl=${{ secrets.PLANNING_CENTER_BASE_URL }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
